apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: productpage
spec:
  components:
    - name: productpage
      type: deployment
      settings:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: productpage-v1
          labels:
            app: productpage
            version: v1
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: productpage
              version: v1
          template:
            metadata:
              labels:
                app: productpage
                version: v1
            spec:
              serviceAccountName: bookinfo-productpage
              containers:
                - name: productpage
                  image: istio/examples-bookinfo-productpage-v1:1.15.1
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 9080
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp
              volumes:
                - name: tmp
                  emptyDir: {}
